### ISSUE TITLE
As a new user, I want to create an account by providing my personal details, so that I can login afterwards with my credentials

### ISSUE THREAD

**Issue by OllieWebb** [ChrisRaynerSG/AutomatedWebTestingProject#2]

**Comment by OllieWebb** [comment]
test note

**Comment by Patrikturc** [comment]
2.1
@Happy
Given I am on the login page 
When I enter a valid name and email address
And I click on the sign up button 
Then I am sent to signup page

**Comment by Patrikturc** [comment]
2.2 
@Happy
Given I am on the Signup page
When I enter correct information into all required fields
Then I am successfully registered

**Comment by ChrisRaynerSG** [comment]
2.3
@sad
Scenario: register with pre-existing email address
Given I am on the login page
    And I enter a valid name "abc"
    And I enter email address that is already registered "abc@abc.abc"
    When I click on the sign up button
    Then error "Email Address already exist!" should be displayed

**Comment by ChrisRaynerSG** [comment]
2.4
@sad
Scenario: register without providing all required fields
Given I am on the signup page
And I have not provided information into all required fields
When I click create account
Then I should be informed which fields are missing
