### ISSUE TITLE
As a registered user, I want to be able to log in to my account, if I provide the correct credentials

### ISSUE THREAD

**Issue by ChrisRaynerSG** [ChrisRaynerSG/AutomatedWebTestingProject#3]

**Comment by OllieWebb** [comment]
3.1: @Happy
Given I am on the login page
    And I have entered the username ""
    And I have entered the password ""
    When I click the login button
    Then I should land on the home page

**Comment by OllieWebb** [comment]
3.2: @Sad
Given I am on the login page
And I have entered the username ""
And I have entered the password "wrong_passwrd"
When I click the login button
Then I should land get an error message "incorrect password"
